### ISSUE TITLE
bad dependency qobo/cakephp-utils

### ISSUE THREAD

**Issue by Kraloz** [QoboLtd/cakephp-calendar#141]
The lastest version of this package depends on `qobo/cakephp-utils` which depends on
 `burzum/cakephp-file-storage: dev-branch-2.0` which doesn't exists anymore, now it's called  
`burzum/cakephp-file-storage: 2.0.0`

![image](https://user-images.githubusercontent.com/20146634/61062024-cc264d80-a3d3-11e9-8cfe-b185b2ca1558.png)

**Comment by anvyst** [comment]
@Kraloz good day, 

The problem derives from outdated version of `burzum/cakephp-file-storage` package we're using. Fabien introduced upgraded `cakephp-migrations` in his recent plugin releases, that we haven't tested yet in our infrastructure. Thus we use his plugin in forked version. You can check similar setup of `qobo/cakephp-file-storage` like in here:

https://github.com/QoboLtd/cakephp-csv-migrations/blob/master/composer.json

**Comment by Kraloz** [comment]
I didn't solve this but also I'm not working anymore with PHP
